config/routes.rb
Hackapp::Application.routes.draw do

  root 'schools#index'
  resources :schools

  get 'filter' => 'schools#filter', as: 'filter'

  

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :locations
  has_many :schools, through: :locations
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :locations
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :school
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :city
  belongs_to :school
  has_many :courses
  has_one :address
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :employees
  has_many :locations
  has_many :cities, through: :locations
  has_many :courses, through: :locations

  mount_uploader :attachment, ImageUploader

  include PgSearch
  pg_search_scope :search, against: [:name, :city, :stack, :price],
    using: {tsearch: {dictionary: "english"}}

  def self.text_search(query)
    if query.present?
      search(query)
    else
      School.all
    end
  end

  def self.filter(filter_params = nil)

    if filter_params

      schools = School.all

      puts schools

      selection = filter_params[:cities].values

      locations = selection.inject(School) { |schools, city| schools.where('city IN (?)', selection) }

      if locations.empty?
        locations = schools
      end

      tech = selection.inject(School) { |schools, city| schools.where('stack IN (?)', selection) }

      if tech.empty?
        tech = schools
      end

      results = []

      schools.each do |school|
        if tech.include?(school) && locations.include?(school)
          results << school
        end
      end

      results

    else
      School.all
    end
  end
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json

  def index
    @schools = School.text_search(params[:query]).filter(params[:filter])
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  def search
    index
    render :index
  end

  def filter

    index

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :city, :street, :state, :zip, :description, :price, :duration, :stack, :logo, :video, :website, :email, :twitter, :facebook)
    end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_filter.html.erb
<%= form_tag filter_path, :remote => true, method: :get do %>
  
<i class="location fa fa-chevron-down fa-2x"> Location</i>
<div class="filter-category city-buttons">

    <div><%= check_box('filter[cities]', 'Akron', {}, 'Akron')%>
    <%= label_tag 'Akron', 'Akron'%></div>

    <div><%= check_box('filter[cities]', 'Albuquerque', {}, 'Albuquerque')%>
    <%= label_tag 'Albuquerque', 'Albuquerque'%></div>

    <div><%= check_box('filter[cities]', 'Austin', {}, 'Austin')%>
    <%= label_tag 'Austin', 'Austin'%></div>

    <div><%= check_box('filter[cities]', 'Boston', {}, 'Boston')%>
    <%= label_tag 'Boston', 'Boston'%></div>

    <div><%= check_box('filter[cities]', 'Cambridge', {}, 'Cambridge')%>
    <%= label_tag 'Cambridge', 'Cambridge'%></div>

    <div><%= check_box('filter[cities]', 'Chicago', {}, 'Chicago')%>
    <%= label_tag 'Chicago', 'Chicago'%></div>

    <div><%= check_box('filter[cities]', 'Denver', {}, 'Denver')%>
    <%= label_tag 'Denver', 'Denver'%></div>

    <div><%= check_box('filter[cities]', 'Detroit', {}, 'Detroit')%>
    <%= label_tag 'Detroit', 'Detroit'%></div>

    <div><%= check_box('filter[cities]', 'Kansas City', {}, 'Kansas City')%>
    <%= label_tag 'Kansas City', 'Kansas City'%></div>

    <div><%= check_box('filter[cities]', 'Las Vegas', {}, 'Las Vegas')%>
    <%= label_tag 'Las Vegas', 'Las Vegas'%></div>

    <div><%= check_box('filter[cities]', 'London', {}, 'London')%>
    <%= label_tag 'London', 'London'%></div>

    <div><%= check_box('filter[cities]', 'Montreal', {}, 'Montreal')%>
    <%= label_tag 'Montreal', 'Montreal'%></div>

    <div><%= check_box('filter[cities]', 'Nashville', {}, 'Nashville')%>
    <%= label_tag 'Nashville', 'Nashville'%></div>

    <div><%= check_box('filter[cities]', 'New York', {}, 'New York')%>
    <%= label_tag 'New York', 'New York'%></div>

    <div><%= check_box('filter[cities]', 'Portland', {}, 'Portland')%>
    <%= label_tag 'Portland', 'Portland'%></div>

    <div><%= check_box('filter[cities]', 'Provo', {}, 'Provo')%>
    <%= label_tag 'Provo', 'Provo'%></div>

    <div><%= check_box('filter[cities]', 'Salt Lake City', {}, 'Salt Lake City')%>
    <%= label_tag 'Salt Lake City', 'Salt Lake City'%></div>

    <div><%= check_box('filter[cities]', 'San Francisco', {}, 'San Francisco')%>
    <%= label_tag 'San Francisco', 'San Francisco'%></div>

    <div><%= check_box('filter[cities]', 'Seattle', {}, 'Seattle')%>
    <%= label_tag 'Seattle', 'Seattle'%></div>

    <div><%= check_box('filter[cities]', 'Sydney', {}, 'Sydney')%>
    <%= label_tag 'Sydney', 'Sydney'%></div>

    <div><%= check_box('filter[cities]', 'Toronto', {}, 'Toronto')%>
    <%= label_tag 'Toronto', 'Toronto'%></div>

    <div><%= check_box('filter[cities]', 'Vancouver', {}, 'Vancouver')%>
    <%= label_tag 'Vancouver', 'Vancouver'%></div>
</div>

<div class="filter-category price-buttons">

    <div><%= check_box('filter[cities]', '< 7,000', {}, '< 7,000')%>
    <%= label_tag '< 7,000', '< 7,000'%></div>

    <div><%= check_box('filter[cities]', '7-12,000', {}, '7-12,000')%>
    <%= label_tag '7-12,000', '7-12,000'%></div>

    <div><%= check_box('filter[cities]', '> 12,000', {}, '> 12,000')%>
    <%= label_tag '> 12,000', '> 12,000'%></div>

</div>

<i class="tech fa fa-chevron-down fa-2x"> Technology</i>
<div class="filter-category tech-buttons">

    <div><%= check_box('filter[cities]', 'Android', {}, 'Android')%>
    <%= label_tag 'Android', 'Android'%></div>

    <div><%= check_box('filter[cities]', 'Entrepreneurship', {}, 'Entrepreneurship')%>
    <%= label_tag 'Entrepreneurship', 'Entrepreneurship'%></div>

    <div><%= check_box('filter[cities]', 'iOS', {}, 'iOS')%>
    <%= label_tag 'iOS', 'iOS'%></div>

    <div><%= check_box('filter[cities]', 'Javascript', {}, 'Javascript')%>
    <%= label_tag 'Javascript', 'Javascript'%></div>

    <div><%= check_box('filter[cities]', 'Python', {}, 'Python')%>
    <%= label_tag 'Python', 'Python'%></div>

    <div><%= check_box('filter[cities]', 'Ruby on Rails', {}, 'Ruby on Rails' )%>
    <%= label_tag 'Ruby', 'Ruby'%></div>

    
</div>

<%= submit_tag 'Apply Filters', name: "filter-button" %>

<% end %>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :stack %><br>
    <%= f.text_field :stack %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/filter.js.erb
(function () {

 $('.content').empty();

results.add(<%= raw @schools.to_json %>);

	//index.remove(<%= raw @schools.to_json %>);
	// index.reset(<%= raw @schools.to_json %>)

	// results.add(<%= raw @schools.to_json %>);

})();

app/views/schools/index.html.erb
<div class="trunk">
<!--   <aside class="filter">
    <div class="filter-button">
      <i class="fa fa-filter"> Filter</i>
    </div>
  </aside> -->

  <div class="directory content">
    <aside class="filter">
      <div class="filter-area">
        <div class="filter-bar">
          <%= render 'filter' %>
        </div>
      </div>
    </aside>
  </div>

  <div id="templates">
    <script class="school", type="text/template", style="display:none">
      <div class="schoollogobox">
        <%= link_to "schools/{{id}}" do %>
          <img src="{{logo}}">
        <% end %>
      </div>
      <div class="schooltextbox">
        <h4> <%= link_to "{{name}}", "schools/{{id}}" %> </h4>
        <h6> {{city}} {{state}} </h6>
      </div>
    </script>
  </div>

  <% content_for :javascript do %>
  <script type="text/javascript">

      var index = new SchoolCollection();
      var results = new SchoolCollection();

      var indexView = new SchoolIndexView({
        collection: index,
        el: '.content'
      });

      var resultsView = new SchoolIndexView({
        collection: results,
        el: '.content'
      });

      var schools = <%= raw @schools.to_json %>

      index.add(schools);
  </script>
  <% end %>
</div>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.haml
.content.trunk
  .main
    .school-top
      .school-logo=image_tag @school.logo
      .school-name-container
        .school-name
          %h2= @school.name
    - if @school.video?
      .school-media
        %strong.section-header Media
        %br
        .media-wrap
          <iframe width="560" height="315" src= "//www.youtube.com/embed/#{@school.video}" frameborder="0" allowfullscreen></iframe>
    .school-about
      %strong.section-header About
      %br
      %p
        = @school.description
    .disqus_thread
      = raw disqus_thread
  %aside.sidebar
    .shade
    %ul.sidebar__items
      %li
        %button.apply-here= link_to "Apply Here", @school.website, {target: "_blank"}
      %li
        .school-stats
          %h4= @school.city
          %h4= @school.duration
          %h4= @school.stack
          %h4= @school.price
      %li
        %div.school-links
          %p
            %i.fa.fa-link.fa-2x
            = link_to @school.name, @school.website
          %p
            %i.fa.fa-envelope.fa-2x
            = mail_to @school.email
          %p
            %i.fa.fa-twitter.fa-2x
            = link_to "Twitter", @school.twitter
          %p
            %i.fa.fa-facebook.fa-2x
            = link_to "Facebook", @school.facebook
          %p
            %i.fa.fa-location-arrow.fa-2x
            = @school.street
            %br
            .address
              = @school.city + ","
              = @school.state
              = @school.zip